---
name: OSSF Scorecard

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 12 * * 1'
  push:
    branches: [main]

jobs:
  ossf-scorecard:
    runs-on: ubuntu-latest
    steps:
      - name: OSSF Scorecard Action
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
      - name: Upload Scorecard results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@19b2f06db2b6f5108140aeb04014ef02b648f789 # v4
        with:
          sarif_file: results.sarif
